name: STP_ViT_S
precision: 16
exp_path: experiments/STP_vits_pre
base: ./config/path/imagenet_path_config.yml
datasets:
    num_workers: 12
    batch_size: 128
    point_level_aug: false
    train:
        type: PretrainImageNetDataset
    eval:
        type: PretrainImageNetDataset        

       
train:    
    type: TrainerModelPretraining   
    epoch: 100  
    save_every: 10
    base_lr: !!float 1.5e-4
    weight_decay: 0.03 
    warmup_epoch: 20
    cycle_epoch: 100

    
