name: STP_ViT_S
precision: 16
exp_path: experiments/STP_vits_pre
base: ./config/ours/base/ours_pretraining_base.yml
    
train:    
    base_lr: !!float 1.5e-4
    warmup_epoch: 20   
    epoch: 100
    cycle_epoch: 100
